security:
  oauth2:
    resource:
      filter-order: 3
      
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: JWT Example Realm
  
  jwt:
    client-id: jaimetest
    client-secret: test
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid